apiVersion: v1
kind:  Service
metadata:
  name: ecomm-page-service
  labels:
    name: nginx   # ✅ this must match the Service selector
spec:
  type: NodePort
  selector:
    app: nginx  
  ports:
    - port: 80
      nodePort: 30008
