services:
  admin:
    build: ./admin
    image: deepika033/login_page:1.1
    ports:
      - "8080:80"
  student:
    build: ./student
    image: deepika033/login_page:2.1
    ports:
      - "8081:80"
  trainer:
    build: ./trainer
    image: deepika033/login_page:3.1
    ports:
      - "8082:80"
  ecommm:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - /home/ubuntu/login_page/ecommm:/usr/share/nginx/html  
  foood:
    image: nginx
    ports:
      - "8084:80"
    volumes:
      - /home/ubuntu/login_page/foood:/usr/share/nginx/html  
  nginx:
    image: nginx
    ports:        
      - "80:80"



