services:
  admin:
    build: ./admin
    image: deepika033/login_page:1.1
    ports:
      - "8080:80"
  student:
    build: ./student
    image: deepika033/login_page:2.1
    ports:
      - "8081:80"
  trainer:
    build: ./admin
    image: deepika033/login_page:3.1
    ports:
      - "8082:80"
  nginx:
    image: nginx
    ports:        
      - "80:80"


