apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: c1
        image: deepika033/food
        ports:
        - containerPort: 80
