apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: dev  # Correctly set the namespace here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: c1
        image: deepika033/login_page:5.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: dev
  labels:
    app: login   # ✅ this must match the Service selector
spec:
  type: NodePort
  selector:
    app: login
  ports:
    - port: 80
      nodePort: 30007
