apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      namespace: dev
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: deepika033/login_page:5.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind:  Service
metadata:
  name: login-service
  namespace: dev
  labels:
    app: ngnix   # ✅ this must match the Service selector
spec:
  type: NodePort
  selector:
    app: nginx  
  ports:
    - port: 80
      nodePort: 30007
