apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-1
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  - name: c2
    image: nginx
    ports:
    - containerPort: 80
  - name: c3
    image: deepika033/login_page:3.1
    ports:
    - containerPort: 8080
