apiVersion: v1
kind: Pod
metadata:
  name: ecomm-page-service
  labels:
    app: ecomm-page   # ✅ this must match the Service selector
spec:
  type: NodePort
  selector:
    app: nginx  
  ports:
    - port: 80
      nodePort: 30007
